name = "WitnessIndependenceProofs"
version = "0.1.0"
defaultTargets = ["WitnessIndependenceProofs"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "8850ed93863d6ce27210a673f9ed235a4e8a2994"

[[lean_lib]]
name = "WitnessIndependenceProofs"
